management.endpoints.web.exposure.include: '*'

spring:
  output:
    ansi:
      enabled: always
  application.name: quote-collector
  datasource:
    password: password
    username: sa
    url: jdbc:h2:mem:testdb
  jpa:
    open-in-view: false
  h2:
    console:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

infra:
  quote:
    url: https://quotes15.p.rapidapi.com
    api_key: bf6b2580acmsh746c8a3455d69ecp18d011jsn2612d1a1d48a
    host: quotes15.p.rapidapi.com

feign:
  client:
    config:
      quote:
        # show the http request / response of feign client
        logger-level: full

logging.level:
  # whole application
  com.example.playground: DEBUG
  # datasource proxy showing sql requests
  net.ttddyy.dsproxy.listener: debug
