management.endpoints.web.exposure.include: '*'

spring:
  sleuth:
    jdbc:
      enabled: false
  output:
    ansi:
      enabled: always
  application.name: quote-collector
  datasource:
    password: password
    username: sa
    url: jdbc:h2:mem:testdb
  jpa:
    open-in-view: false
  h2:
    console:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

services:
  rapid-api:
    quotes:
      url: https://quotes15.p.rapidapi.com
      api_key: bf6b2580acmsh746c8a3455d69ecp18d011jsn2612d1a1d48a
      host: quotes15.p.rapidapi.com

feign:
  client:
    config:
      quote:
        # show the http request / response of feign client
        logger-level: full

logging.level:
  # whole application
  com.example.playground: DEBUG
  com.example.playground.security: INFO
  # datasource proxy showing sql requests
  net.ttddyy.dsproxy.listener: debug

app:
  zone-id: "Europe/Paris"
  job.gift.cron: "0 * * * * *"
  features:
    gift:
      pack.size: 2

